### PR TITLE
changePrizePool and changePrizeArray implimented 

### PR DESCRIPTION
**Pull request by yomanthunder**
Resolving https://github.com/BlocSoc-iitr/DappHack/issues/15

- Two view functions for both poolPrize change and prizeArray change
- Two function to changePrizePool and ChangePrizeArray that can only be access by sponsor , takes in the prizePool or prizeArray (only one argument functions)
- Basic tests written using mocha and chai

### CODE REVIEW

**Comment by yomanthunder** [comment]
@lordshashank i think having sponsor number as a parameter make you more prone to attacks , our modifier only check whether you are a sponsor or not meaning others sponsor can tamper with my prizepool or prizearray (which can potentially be stopped with some basic code but makes things more complicated tho)
imo this does create a new feature where other sponsors can sponsor you based on your sponsor Number  (but in general in hackathons i have never seen a sponsor sponsoring other sponsor)

**Comment by lordshashank** [comment]
@yomanthunder , this makes sense, your implementation would be good for now. Just do following two improvements.
- sponsorToId array just get initialized for msg.sender in sponsor signup, initialize it for all addresses in _sponsor with same id as this would enable any of them to do prize updates.
- check the balances of sponsor before and after running the functions in tests so as to make sure the amount gets transferred successfully.
This is a great solution. Thank you for your contribution.

**Comment by yomanthunder** [comment]
- I have made the required changes , you can merge the pull request

**Comment by lordshashank** [comment]
LFG🚀

**Review by lordshashank — COMMENTED** [review]
GOOD TO GO

**Pull request merged**
